[package]
name = "aldis"
version = "0.2.2"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/mjonuschat/aldis"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.5.58", features = ["derive"] }
dfu-core = "0.11.1"
dfu-nusb = "0.2.0"
nusb = "0.2.7"
picoboot = { version = "0.2.6", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
serialport = { version = "4.10.1", default-features = false }
tempfile = "3.23.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["net", "rt"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
ureq = "3.4.1"

socketcan = { version = "4.0.0", default-features = false }

[patch.crates-io]
dfu-core = { git = "https://github.com/mjonuschat/dfu-core", rev = "e0150206498cbb2b1f06c897ba129b5daa841f7a" }
