[package]
name = "mcu-update"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
dfu-rs = "0.2.1"
futures = "0.3.31"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
serialport = { version = "4.10.1", default-features = false }
ureq = "3.4.1"

[target.'cfg(target_os = "linux")'.dependencies]
socketcan = { version = "4.0.0", default-features = false }
