[package]
name = "mcu-update"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
dfu-core = "0.11.1"
dfu-nusb = "0.2.0"
git2 = { version = "0.20.4", default-features = false, features = ["https", "vendored-libgit2"] }
nusb = "0.2.7"
picoboot = { version = "0.2.6", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
serialport = { version = "4.10.1", default-features = false }
tokio = { version = "1.53.1", features = ["net", "rt"] }
ureq = "3.4.1"

socketcan = { version = "4.0.0", default-features = false }

[patch.crates-io]
dfu-core = { git = "https://github.com/mjonuschat/dfu-core", rev = "e0150206498cbb2b1f06c897ba129b5daa841f7a" }
